#load "Microsoft.Extensions.Configuration.fsx" 
#load "Microsoft.Extensions.Configuration.FileExtensions.fsx" 
#load "System.Text.Json.fsx" 
#load "System.Threading.Tasks.Extensions.fsx" 
#r "../../../../packages/other/Microsoft.Extensions.Configuration.Json/lib/netstandard2.0/Microsoft.Extensions.Configuration.Json.dll" 