#load "System.Collections.Immutable.fsx" 
#load "System.Memory.fsx" 
#load "System.Reflection.Metadata.fsx" 
#load "System.Runtime.CompilerServices.Unsafe.fsx" 
#load "System.Text.Encoding.CodePages.fsx" 
#load "System.Threading.Tasks.Extensions.fsx" 
#r "../../../../packages/other/Microsoft.CodeAnalysis.Common/lib/netstandard2.0/Microsoft.CodeAnalysis.dll" 