#load "System.Linq.csx" 
#load "System.Linq.Expressions.csx" 
#load "System.ObjectModel.csx" 
#load "System.Threading.csx" 
#r "../../../../packages/other/System.Dynamic.Runtime/lib/netstandard1.3/System.Dynamic.Runtime.dll" 