#load "System.Linq.fsx" 
#load "System.Text.RegularExpressions.fsx" 
#load "System.Threading.fsx" 
#load "System.Xml.ReaderWriter.fsx" 
#load "System.Xml.XmlDocument.fsx" 
#r "../../../../packages/other/System.Xml.XmlSerializer/lib/netstandard1.3/System.Xml.XmlSerializer.dll" 