#load "Microsoft.Bcl.AsyncInterfaces.fsx" 
#load "System.Memory.fsx" 
#load "System.Runtime.CompilerServices.Unsafe.fsx" 
#load "System.Text.Encodings.Web.fsx" 
#load "System.Threading.Tasks.Extensions.fsx" 
#r "../../../../packages/other/System.Text.Json/lib/netstandard2.0/System.Text.Json.dll" 