#load "Microsoft.Extensions.Configuration.csx" 
#load "Microsoft.Extensions.DependencyInjection.csx" 
#load "Microsoft.Extensions.FileProviders.Physical.csx" 
#load "Microsoft.Extensions.Hosting.Abstractions.csx" 
#load "Microsoft.Extensions.Logging.csx" 