#load "Microsoft.Owin.Security.csx" 
#load "Newtonsoft.Json.csx" 
#r "Microsoft.CSharp" 
#r "System.Security" 
#r "../../../packages/Microsoft.AspNet.SignalR.Core/lib/net45/Microsoft.AspNet.SignalR.Core.dll" 