#load "System.Private.ServiceModel.fsx" 
#load "System.ServiceModel.Primitives.fsx" 
#r "System.ServiceModel" 
#r "System" 
#r "../../../packages/System.ServiceModel.Duplex/lib/net461/System.ServiceModel.Duplex.dll" 