#load "CommonServiceLocator.fsx" 
#load "Microsoft.Owin.fsx" 
#load "Owin.fsx" 
#load "WebSharper.fsx" 
#load "WebSharper.Owin.fsx" 
#r "System.Configuration" 
#r "../../../packages/WebSharper.Owin.WebSocket/lib/net461/Owin.WebSocket.dll" 
#r "../../../packages/WebSharper.Owin.WebSocket/lib/net461/WebSharper.Owin.WebSocket.dll" 