#load "Microsoft.AspNetCore.Mvc.Razor.fsx" 
#load "Microsoft.AspNetCore.Razor.Runtime.fsx" 
#load "Microsoft.AspNetCore.Routing.Abstractions.fsx" 
#load "Microsoft.Extensions.Caching.Memory.fsx" 
#load "Microsoft.Extensions.Primitives.fsx" 