#load "Microsoft.IdentityModel.Tokens.fsx" 
#load "Microsoft.IdentityModel.Xml.fsx" 
#r "Microsoft.CSharp" 
#r "System" 
#r "System.Net.Http" 
#r "System.Runtime.Serialization" 
#r "../../../../packages/test2/Microsoft.IdentityModel.Tokens.Saml/lib/net451/Microsoft.IdentityModel.Tokens.Saml.dll" 