#load "System.Security.Cryptography.Cng.csx" 
#r "System.Security" 
#r "mscorlib" 
#r "System" 
#r "../../../../packages/test2/System.Security.Cryptography.Pkcs/lib/net46/System.Security.Cryptography.Pkcs.dll" 