#load "System.IO.csx" 
#load "System.Net.Primitives.csx" 
#load "System.Runtime.csx" 
#load "System.Threading.Tasks.csx" 
#r "System" 
#r "mscorlib" 
#r "../../../../packages/test2/System.Net.Sockets/lib/net46/System.Net.Sockets.dll" 