#load "Microsoft.Win32.Registry.csx" 
#load "System.Security.Principal.Windows.csx" 
#load "System.Text.Encoding.CodePages.csx" 
#r "System.Data" 
#r "mscorlib" 
#r "System.Xml" 
#r "../../../../packages/test2/System.Data.SqlClient/lib/net46/System.Data.SqlClient.dll" 