#load "Microsoft.AspNetCore.Authentication.Core.csx" 
#load "Microsoft.AspNetCore.Hosting.csx" 
#load "Microsoft.Net.Http.Headers.csx" 
#load "Microsoft.Win32.Registry.csx" 
#load "System.Security.Principal.Windows.csx" 