#load "Microsoft.IdentityModel.Tokens.fsx" 
#load "Newtonsoft.Json.fsx" 
#r "Microsoft.CSharp" 
#r "System" 
#r "../../../../packages/test/Microsoft.IdentityModel.JsonWebTokens/lib/net451/Microsoft.IdentityModel.JsonWebTokens.dll" 