#load "Microsoft.IdentityModel.Protocols.fsx" 
#load "Newtonsoft.Json.fsx" 
#load "System.Dynamic.Runtime.fsx" 
#load "System.IdentityModel.Tokens.Jwt.fsx" 
#r "Microsoft.CSharp" 
#r "System" 
#r "System.Net.Http" 
#r "../../../../packages/test/Microsoft.IdentityModel.Protocols.OpenIdConnect/lib/net451/Microsoft.IdentityModel.Protocols.OpenIdConnect.dll" 