#load "System.Buffers.fsx" 
#load "System.Memory.fsx" 
#load "System.Security.Cryptography.Cng.fsx" 
#r "System.Security" 
#r "System" 
#r "../../../../packages/test/System.Security.Cryptography.Pkcs/lib/net46/System.Security.Cryptography.Pkcs.dll" 