#load "Microsoft.Build.Framework.csx" 
#load "Microsoft.Win32.Registry.csx" 
#load "System.Collections.Immutable.csx" 
#load "System.Text.Encoding.CodePages.csx" 
#r "../../../../packages/prozper2/Microsoft.Build.Utilities.Core/lib/netstandard2.0/Microsoft.Build.Utilities.Core.dll" 