#load "Microsoft.Extensions.Configuration.Abstractions.fsx" 
#load "Microsoft.Extensions.DependencyInjection.Abstractions.fsx" 
#load "Microsoft.Extensions.FileProviders.Abstractions.fsx" 
#load "Microsoft.Extensions.Logging.Abstractions.fsx" 
#r "../../../../packages/prozper2/Microsoft.Extensions.Hosting.Abstractions/lib/netstandard2.0/Microsoft.Extensions.Hosting.Abstractions.dll" 