#load "Microsoft.AspNet.WebApi.Client.fsx" 
#load "Microsoft.AspNetCore.Http.fsx" 
#load "Microsoft.AspNetCore.Mvc.Formatters.Json.fsx" 
#load "Microsoft.AspNetCore.Mvc.WebApiCompatShim.fsx" 
#load "Microsoft.AspNetCore.Routing.fsx" 
#load "Microsoft.Azure.WebJobs.fsx" 
#r "../../../../packages/prozper2/Microsoft.Azure.WebJobs.Extensions.Http/lib/netstandard2.0/Microsoft.Azure.WebJobs.Extensions.Http.dll" 