#load "Microsoft.AspNet.WebApi.Client.fsx" 
#load "Microsoft.AspNetCore.Mvc.Core.fsx" 
#load "Microsoft.AspNetCore.Mvc.Formatters.Json.fsx" 
#load "Microsoft.AspNetCore.WebUtilities.fsx" 
#r "../../../../packages/prozper2/Microsoft.AspNetCore.Mvc.WebApiCompatShim/lib/netstandard2.0/Microsoft.AspNetCore.Mvc.WebApiCompatShim.dll" 