#load "System.Linq.fsx" 
#load "System.Linq.Expressions.fsx" 
#load "System.ObjectModel.fsx" 
#load "System.Reflection.Emit.fsx" 
#load "System.Reflection.Emit.ILGeneration.fsx" 
#load "System.Threading.fsx" 
#r "../../../../packages/prozper2/System.Dynamic.Runtime/lib/netstandard1.3/System.Dynamic.Runtime.dll" 