#load "System.Xml.XmlDocument.fsx" 
#load "System.Xml.XPath.fsx" 
#r "System" 
#r "System.Xml" 
#r "../../../../packages/testing/System.Xml.XPath.XmlDocument/lib/net46/System.Xml.XPath.XmlDocument.dll" 