#load "Microsoft.Build.Framework.csx" 
#load "Microsoft.Win32.Registry.csx" 
#load "System.Collections.Immutable.csx" 
#load "System.Security.Permissions.csx" 
#load "System.Text.Encoding.CodePages.csx" 
#r "System.Configuration" 