#load "System.Security.Cryptography.ProtectedData.csx" 
#load "System.Security.Permissions.csx" 
#r "System" 
#r "System.Configuration" 
#r "System.Drawing" 
#r "System.Xml" 
#r "mscorlib" 
#r "../../../../packages/fsharp47/System.Configuration.ConfigurationManager/lib/net461/System.Configuration.ConfigurationManager.dll" 