#load "System.Buffers.csx" 
#load "System.Memory.csx" 
#load "System.Security.AccessControl.csx" 
#load "System.Security.Principal.Windows.csx" 
#r "mscorlib" 
#r "../../../../packages/fsharp47/System.IO.FileSystem.AccessControl/lib/net461/System.IO.FileSystem.AccessControl.dll" 