#load "System.Private.ServiceModel.fsx" 
#load "System.ServiceModel.Primitives.fsx" 
#r "System.ServiceModel" 
#r "System.IdentityModel" 
#r "../../../../packages/fsharp47/System.ServiceModel.Http/lib/net461/System.ServiceModel.Http.dll" 