#load "System.Private.ServiceModel.csx" 
#load "System.ServiceModel.Primitives.csx" 
#r "System.ServiceModel" 
#r "System.IdentityModel" 
#r "../../../../packages/fsharp47/System.ServiceModel.Security/lib/net461/System.ServiceModel.Security.dll" 