#load "System.Security.AccessControl.csx" 
#load "System.Security.Principal.Windows.csx" 
#r "System.Core" 
#r "mscorlib" 
#r "../../../../packages/fsharp47/System.IO.Pipes.AccessControl/lib/net461/System.IO.Pipes.AccessControl.dll" 