#load "System.Buffers.fsx" 
#load "System.Memory.fsx" 
#load "System.Security.AccessControl.fsx" 
#load "System.Security.Principal.Windows.fsx" 
#r "../../../../packages/fsharp47/System.IO.FileSystem.AccessControl/lib/net461/System.IO.FileSystem.AccessControl.dll" 