#load "System.Memory.csx" 
#load "System.Security.Cryptography.Pkcs.csx" 
#load "System.Security.Permissions.csx" 
#r "System" 
#r "System.Security" 
#r "System.Xml" 
#r "mscorlib" 
#r "../../../../packages/fsharp47/System.Security.Cryptography.Xml/lib/net461/System.Security.Cryptography.Xml.dll" 