#load "System.Memory.fsx" 
#load "System.Security.AccessControl.fsx" 
#load "System.Security.Principal.Windows.fsx" 
#r "System" 
#r "../../../../packages/fsharp47/System.Threading.AccessControl/lib/net461/System.Threading.AccessControl.dll" 