#load "EPPlus.Interfaces.csx" 
#load "EPPlus.System.Drawing.csx" 
#load "Microsoft.Extensions.Configuration.Json.csx" 
#load "Microsoft.IO.RecyclableMemoryStream.csx" 
#load "System.Drawing.Primitives.csx" 
#load "System.Security.Cryptography.Pkcs.csx" 
#load "System.Text.Encoding.CodePages.csx" 
#r "../../../../packages/other/EPPlus/lib/netstandard2.0/EPPlus.dll" 