#load "Microsoft.Bcl.AsyncInterfaces.csx" 
#load "Microsoft.Extensions.Configuration.Abstractions.csx" 
#load "Microsoft.Extensions.DependencyInjection.Abstractions.csx" 
#load "Microsoft.Extensions.FileProviders.Abstractions.csx" 
#load "Microsoft.Extensions.Logging.Abstractions.csx" 
#r "../../../../packages/other/Microsoft.Extensions.Hosting.Abstractions/lib/netstandard2.0/Microsoft.Extensions.Hosting.Abstractions.dll" 