#load "System.Runtime.CompilerServices.Unsafe.csx" 
#r "../../../../packages/other/Microsoft.Diagnostics.Tracing.TraceEvent/lib/netstandard2.0/TraceReloggerLib.dll" 
#r "../../../../packages/other/Microsoft.Diagnostics.Tracing.TraceEvent/lib/netstandard2.0/OSExtensions.dll" 
#r "../../../../packages/other/Microsoft.Diagnostics.Tracing.TraceEvent/lib/netstandard2.0/Microsoft.Diagnostics.FastSerialization.dll" 
#r "../../../../packages/other/Microsoft.Diagnostics.Tracing.TraceEvent/lib/netstandard2.0/Dia2Lib.dll" 
#r "../../../../packages/other/Microsoft.Diagnostics.Tracing.TraceEvent/lib/netstandard2.0/Microsoft.Diagnostics.Tracing.TraceEvent.dll" 