#load "Microsoft.Bcl.AsyncInterfaces.csx" 
#load "System.Buffers.csx" 
#load "System.Memory.csx" 
#load "System.Numerics.Vectors.csx" 
#load "System.Runtime.CompilerServices.Unsafe.csx" 
#load "System.Text.Encodings.Web.csx" 
#load "System.Threading.Tasks.Extensions.csx" 
#r "../../../../packages/other/System.Text.Json/lib/netstandard2.0/System.Text.Json.dll" 