#load "Microsoft.AspNetCore.Http.Abstractions.csx" 
#load "Microsoft.Extensions.FileProviders.Abstractions.csx" 
#load "Microsoft.Net.Http.Headers.csx" 
#load "System.Buffers.csx" 
#r "../../../../packages/prozper/Microsoft.AspNetCore.Http.Extensions/lib/netstandard2.0/Microsoft.AspNetCore.Http.Extensions.dll" 