#load "System.Collections.Specialized.fsx" 
#load "System.ComponentModel.fsx" 
#load "System.ComponentModel.TypeConverter.fsx" 
#load "System.Diagnostics.TraceSource.fsx" 
#load "System.Dynamic.Runtime.fsx" 
#load "System.Reflection.Emit.fsx" 
#load "System.Xml.XmlDocument.fsx" 
#r "../../../../packages/testing/Castle.Core/lib/netstandard1.5/Castle.Core.dll" 