#load "System.Collections.Specialized.csx" 
#load "System.ComponentModel.csx" 
#load "System.ComponentModel.TypeConverter.csx" 
#load "System.Diagnostics.TraceSource.csx" 
#load "System.Dynamic.Runtime.csx" 
#load "System.Reflection.Emit.csx" 
#load "System.Xml.XmlDocument.csx" 
#r "../../../../packages/testing/Castle.Core/lib/netstandard1.5/Castle.Core.dll" 