#load "Microsoft.Extensions.Configuration.fsx" 
#load "Microsoft.Extensions.DependencyInjection.fsx" 
#load "Microsoft.Extensions.FileProviders.Physical.fsx" 
#load "Microsoft.Extensions.Hosting.Abstractions.fsx" 
#load "Microsoft.Extensions.Logging.fsx" 
#r "../../../../packages/test2/Microsoft.Extensions.Hosting/lib/netstandard2.0/Microsoft.Extensions.Hosting.dll" 