#load "MessagePack.csx" 
#load "Microsoft.AspNetCore.SignalR.Core.csx" 
#load "Microsoft.Extensions.Options.csx" 
#load "StackExchange.Redis.StrongName.csx" 
#r "../../../../packages/test2/Microsoft.AspNetCore.SignalR.Redis/lib/netstandard2.0/Microsoft.AspNetCore.SignalR.Redis.dll" 