#load "Microsoft.AspNetCore.Hosting.Abstractions.csx" 
#load "Microsoft.AspNetCore.Http.csx" 
#load "Microsoft.AspNetCore.Http.Extensions.csx" 
#load "Microsoft.Extensions.Configuration.Binder.csx" 
#load "Microsoft.Extensions.Options.csx" 
#r "../../../../packages/test2/Microsoft.AspNetCore.HttpsPolicy/lib/netstandard2.0/Microsoft.AspNetCore.HttpsPolicy.dll" 