#load "Microsoft.Extensions.Configuration.csx" 
#load "Microsoft.Extensions.DependencyInjection.csx" 
#load "Microsoft.Extensions.FileProviders.Physical.csx" 
#load "Microsoft.Extensions.Hosting.Abstractions.csx" 
#load "Microsoft.Extensions.Logging.csx" 
#r "../../../../packages/test2/Microsoft.Extensions.Hosting/lib/netstandard2.0/Microsoft.Extensions.Hosting.dll" 