#load "Microsoft.AspNetCore.Mvc.Razor.csx" 
#load "Microsoft.AspNetCore.Razor.Runtime.csx" 
#load "Microsoft.AspNetCore.Routing.Abstractions.csx" 
#load "Microsoft.Extensions.Caching.Memory.csx" 
#load "Microsoft.Extensions.FileSystemGlobbing.csx" 
#load "Microsoft.Extensions.Primitives.csx" 
#r "../../../../packages/test2/Microsoft.AspNetCore.Mvc.TagHelpers/lib/netstandard2.0/Microsoft.AspNetCore.Mvc.TagHelpers.dll" 