#load "Microsoft.AspNetCore.Authorization.fsx" 
#load "Microsoft.AspNetCore.SignalR.Common.fsx" 
#load "Microsoft.AspNetCore.SignalR.Protocols.Json.fsx" 
#load "Microsoft.Extensions.DependencyInjection.Abstractions.fsx" 
#load "Microsoft.Extensions.Logging.Abstractions.fsx" 
#load "System.Reflection.Emit.fsx" 
#load "System.Threading.Channels.fsx" 
#r "../../../../packages/test2/Microsoft.AspNetCore.SignalR.Core/lib/netstandard2.0/Microsoft.AspNetCore.SignalR.Core.dll" 