#load "Microsoft.DotNet.PlatformAbstractions.csx" 
#load "Newtonsoft.Json.csx" 
#load "System.Dynamic.Runtime.csx" 
#load "System.Linq.csx" 
#r "../../../../packages/test2/Microsoft.Extensions.DependencyModel/lib/netstandard1.6/Microsoft.Extensions.DependencyModel.dll" 