#load "Microsoft.AspNetCore.Http.Extensions.csx" 
#load "Microsoft.Extensions.Logging.Abstractions.csx" 
#load "Microsoft.Extensions.Options.csx" 
#load "System.Net.WebSockets.WebSocketProtocol.csx" 
#r "../../../../packages/test2/Microsoft.AspNetCore.WebSockets/lib/netstandard2.0/Microsoft.AspNetCore.WebSockets.dll" 