#load "Microsoft.Extensions.Configuration.EnvironmentVariables.csx" 
#load "Microsoft.Extensions.Configuration.Json.csx" 
#load "Microsoft.Extensions.Logging.csx" 
#load "Microsoft.Extensions.Logging.Abstractions.csx" 
#load "Microsoft.Extensions.Logging.Configuration.csx" 
#r "../../../../packages/test2/Microsoft.Extensions.Logging.AzureAppServices/lib/netstandard2.0/Microsoft.Extensions.Logging.AzureAppServices.dll" 