#load "Microsoft.AspNetCore.Hosting.Abstractions.fsx" 
#load "Microsoft.AspNetCore.Http.Extensions.fsx" 
#load "Microsoft.Extensions.FileProviders.Abstractions.fsx" 
#load "Microsoft.Extensions.Logging.Abstractions.fsx" 
#load "Microsoft.Extensions.WebEncoders.fsx" 
#r "../../../../packages/test2/Microsoft.AspNetCore.StaticFiles/lib/netstandard2.0/Microsoft.AspNetCore.StaticFiles.dll" 