#load "Microsoft.IdentityModel.Logging.csx" 
#load "Microsoft.IdentityModel.Tokens.csx" 
#load "System.Collections.Specialized.csx" 
#load "System.Diagnostics.Contracts.csx" 
#load "System.Net.Http.csx" 
#r "../../../../packages/test/Microsoft.IdentityModel.Protocols/lib/netstandard2.0/Microsoft.IdentityModel.Protocols.dll" 