#load "Microsoft.AspNetCore.DataProtection.csx" 
#load "Microsoft.AspNetCore.Http.Abstractions.csx" 
#load "Microsoft.Extensions.Caching.Abstractions.csx" 
#load "Microsoft.Extensions.Logging.Abstractions.csx" 
#load "Microsoft.Extensions.Options.csx" 
#r "../../../../packages/test/Microsoft.AspNetCore.Session/lib/netstandard2.0/Microsoft.AspNetCore.Session.dll" 