#load "Microsoft.Extensions.Configuration.Abstractions.csx" 
#load "Microsoft.Extensions.Configuration.Binder.csx" 
#load "Microsoft.Extensions.DependencyInjection.Abstractions.csx" 
#load "Microsoft.Extensions.Options.csx" 
#r "../../../../packages/test/Microsoft.Extensions.Options.ConfigurationExtensions/lib/netstandard2.0/Microsoft.Extensions.Options.ConfigurationExtensions.dll" 