#load "System.Net.Http.csx" 
#load "System.Xml.XmlDocument.csx" 
#load "System.Xml.XPath.csx" 
#load "System.Xml.XPath.XmlDocument.csx" 
#r "../../../../packages/test2/HtmlAgilityPack/lib/netstandard2.0/HtmlAgilityPack.dll" 