#load "System.Reflection.Emit.csx" 
#load "System.Reflection.Emit.Lightweight.csx" 
#load "System.Runtime.Serialization.Primitives.csx" 
#load "System.Threading.Tasks.Extensions.csx" 
#r "../../../../packages/test2/MessagePack/lib/netstandard2.0/MessagePack.dll" 