#load "System.Reflection.Emit.fsx" 
#load "System.Reflection.Emit.Lightweight.fsx" 
#load "System.Runtime.Serialization.Primitives.fsx" 
#load "System.Threading.Tasks.Extensions.fsx" 
#r "../../../../packages/test2/MessagePack/lib/netstandard2.0/MessagePack.dll" 