#load "Microsoft.AspNetCore.Authorization.csx" 
#load "Microsoft.AspNetCore.SignalR.Common.csx" 
#load "Microsoft.AspNetCore.SignalR.Protocols.Json.csx" 
#load "Microsoft.Extensions.DependencyInjection.Abstractions.csx" 
#load "Microsoft.Extensions.Logging.Abstractions.csx" 
#load "System.Reflection.Emit.csx" 
#load "System.Threading.Channels.csx" 
#r "../../../../packages/test2/Microsoft.AspNetCore.SignalR.Core/lib/netstandard2.0/Microsoft.AspNetCore.SignalR.Core.dll" 