#load "Microsoft.AspNetCore.Hosting.Abstractions.csx" 
#load "Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.csx" 
#load "Microsoft.Extensions.Logging.Abstractions.csx" 
#load "Microsoft.Extensions.Options.csx" 
#r "../../../../packages/test2/Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv/lib/netstandard2.0/Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.dll" 