#load "Microsoft.AspNetCore.Hosting.Abstractions.fsx" 
#load "Microsoft.AspNetCore.Http.fsx" 
#load "Microsoft.AspNetCore.Http.Extensions.fsx" 
#load "Microsoft.Extensions.Options.fsx" 
#r "../../../../packages/test2/Microsoft.AspNetCore.HostFiltering/lib/netstandard2.0/Microsoft.AspNetCore.HostFiltering.dll" 