#load "Microsoft.Extensions.Configuration.EnvironmentVariables.fsx" 
#load "Microsoft.Extensions.Configuration.Json.fsx" 
#load "Microsoft.Extensions.Logging.fsx" 
#load "Microsoft.Extensions.Logging.Abstractions.fsx" 
#load "Microsoft.Extensions.Logging.Configuration.fsx" 
#r "../../../../packages/test2/Microsoft.Extensions.Logging.AzureAppServices/lib/netstandard2.0/Microsoft.Extensions.Logging.AzureAppServices.dll" 