#load "Microsoft.AspNetCore.Authentication.Core.fsx" 
#load "Microsoft.AspNetCore.Connections.Abstractions.fsx" 
#load "Microsoft.AspNetCore.Hosting.Abstractions.fsx" 
#load "System.IO.Pipelines.fsx" 
#load "System.Security.Principal.Windows.fsx" 
#r "../../../../packages/test2/Microsoft.AspNetCore.Server.IIS/lib/netstandard2.0/Microsoft.AspNetCore.Server.IIS.dll" 