#load "Microsoft.AspNetCore.Connections.Abstractions.csx" 
#load "Microsoft.Extensions.Options.csx" 
#load "Newtonsoft.Json.csx" 
#load "System.Buffers.csx" 
#r "../../../../packages/test2/Microsoft.AspNetCore.SignalR.Common/lib/netstandard2.0/Microsoft.AspNetCore.SignalR.Common.dll" 