#load "Microsoft.AspNetCore.Localization.csx" 
#load "Microsoft.AspNetCore.Mvc.Razor.csx" 
#load "Microsoft.Extensions.DependencyInjection.csx" 
#load "Microsoft.Extensions.Localization.csx" 
#r "../../../../packages/test2/Microsoft.AspNetCore.Mvc.Localization/lib/netstandard2.0/Microsoft.AspNetCore.Mvc.Localization.dll" 