#load "Microsoft.AspNetCore.Cryptography.KeyDerivation.fsx" 
#load "Microsoft.Extensions.Logging.fsx" 
#load "Microsoft.Extensions.Options.fsx" 
#load "System.ComponentModel.Annotations.fsx" 
#r "../../../../packages/test2/Microsoft.Extensions.Identity.Core/lib/netstandard2.0/Microsoft.Extensions.Identity.Core.dll" 