#load "Microsoft.AspNetCore.Cryptography.KeyDerivation.csx" 
#load "Microsoft.Extensions.Logging.csx" 
#load "Microsoft.Extensions.Options.csx" 
#load "System.ComponentModel.Annotations.csx" 
#r "../../../../packages/test2/Microsoft.Extensions.Identity.Core/lib/netstandard2.0/Microsoft.Extensions.Identity.Core.dll" 