#load "Microsoft.Azure.KeyVault.WebKey.fsx" 
#load "Microsoft.Rest.ClientRuntime.fsx" 
#load "Microsoft.Rest.ClientRuntime.Azure.fsx" 
#load "Newtonsoft.Json.fsx" 
#load "System.Net.Http.fsx" 
#r "../../../../packages/test2/Microsoft.Azure.KeyVault/lib/netstandard1.4/Microsoft.Azure.KeyVault.dll" 