#load "Microsoft.Extensions.DependencyInjection.Abstractions.fsx" 
#load "Microsoft.Extensions.Localization.Abstractions.fsx" 
#load "Microsoft.Extensions.Logging.Abstractions.fsx" 
#load "Microsoft.Extensions.Options.fsx" 
#r "../../../../packages/test2/Microsoft.Extensions.Localization/lib/netstandard2.0/Microsoft.Extensions.Localization.dll" 