#load "Microsoft.Azure.KeyVault.csx" 
#load "Microsoft.Azure.Services.AppAuthentication.csx" 
#load "Microsoft.Extensions.Configuration.csx" 
#load "Microsoft.Extensions.Configuration.FileExtensions.csx" 
#r "../../../../packages/test2/Microsoft.Extensions.Configuration.AzureKeyVault/lib/netstandard2.0/Microsoft.Extensions.Configuration.AzureKeyVault.dll" 