#load "Microsoft.AspNetCore.Hosting.Abstractions.fsx" 
#load "Microsoft.AspNetCore.Http.Abstractions.fsx" 
#load "Microsoft.AspNetCore.Http.Extensions.fsx" 
#load "Microsoft.Extensions.FileProviders.Physical.fsx" 
#r "../../../../packages/test2/Microsoft.VisualStudio.Web.BrowserLink/lib/netstandard2.0/Microsoft.VisualStudio.Web.BrowserLink.dll" 