#load "HtmlAgilityPack.csx" 
#load "System.Xml.XDocument.csx" 
#load "WebSharper.csx" 
#r "../../../../packages/test2/WebSharper.UI/lib/netstandard2.0/WebSharper.UI.Templating.Common.dll" 
#r "../../../../packages/test2/WebSharper.UI/lib/netstandard2.0/WebSharper.UI.dll" 
#r "../../../../packages/test2/WebSharper.UI/lib/netstandard2.0/WebSharper.UI.Templating.Runtime.dll" 
#r "../../../../packages/test2/WebSharper.UI/lib/netstandard2.0/WebSharper.UI.Templating.dll" 