#load "System.Buffers.fsx" 
#load "System.Memory.fsx" 
#load "System.Security.AccessControl.fsx" 
#load "System.Security.Principal.Windows.fsx" 
#r "../../../../packages/fsharp47/Microsoft.Win32.Registry/lib/netstandard2.0/Microsoft.Win32.Registry.dll" 