#load "System.Buffers.csx" 
#load "System.Memory.csx" 
#load "System.Security.AccessControl.csx" 
#load "System.Security.Principal.Windows.csx" 
#r "../../../../packages/fsharp47/System.IO.FileSystem.AccessControl/lib/netstandard2.0/System.IO.FileSystem.AccessControl.dll" 