#load "System.Numerics.Vectors.fsx" 
#load "System.Reflection.DispatchProxy.fsx" 
#load "System.Security.Cryptography.Xml.fsx" 
#load "System.Security.Principal.Windows.fsx" 
#r "../../../../packages/fsharp47/System.Private.ServiceModel/lib/netstandard2.0/System.Private.ServiceModel.dll" 