#load "System.Numerics.Vectors.csx" 
#load "System.Reflection.DispatchProxy.csx" 
#load "System.Security.Cryptography.Xml.csx" 
#load "System.Security.Principal.Windows.csx" 
#r "../../../../packages/fsharp47/System.Private.ServiceModel/lib/netstandard2.0/System.Private.ServiceModel.dll" 