#load "Microsoft.Extensions.Configuration.Binder.csx" 
#load "Microsoft.Extensions.DependencyInjection.Abstractions.csx" 
#load "Microsoft.Extensions.Logging.Abstractions.csx" 
#load "Microsoft.Extensions.Options.csx" 
#r "../../../../packages/test/Microsoft.Extensions.Logging/lib/netstandard2.0/Microsoft.Extensions.Logging.dll" 