#load "Microsoft.AspNetCore.DataProtection.fsx" 
#load "Microsoft.AspNetCore.Http.Abstractions.fsx" 
#load "Microsoft.Extensions.Caching.Abstractions.fsx" 
#load "Microsoft.Extensions.Logging.Abstractions.fsx" 
#load "Microsoft.Extensions.Options.fsx" 
#r "../../../../packages/test/Microsoft.AspNetCore.Session/lib/netstandard2.0/Microsoft.AspNetCore.Session.dll" 