#load "Microsoft.AspNetCore.Http.Extensions.csx" 
#load "Microsoft.Extensions.Configuration.Abstractions.csx" 
#load "Microsoft.Extensions.DependencyInjection.Abstractions.csx" 
#load "Microsoft.Extensions.Logging.Abstractions.csx" 
#load "Microsoft.Extensions.Options.csx" 
#r "../../../../packages/test/Microsoft.AspNetCore.Cors/lib/netstandard2.0/Microsoft.AspNetCore.Cors.dll" 