#load "Microsoft.Azure.WebJobs.csx" 
#load "Microsoft.Azure.WebJobs.Extensions.csx" 
#load "Microsoft.Azure.WebJobs.Extensions.Http.csx" 
#load "Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.csx" 
#load "Newtonsoft.Json.csx" 