#load "System.Buffers.csx" 
#load "System.Memory.csx" 
#load "System.Security.AccessControl.csx" 
#load "System.Security.Principal.Windows.csx" 
#r "mscorlib" 
#r "../../../../packages/prozper/Microsoft.Win32.Registry/lib/net46/Microsoft.Win32.Registry.dll" 