#load "System.Resources.ResourceManager.csx" 
#load "System.Runtime.csx" 
#r "System.Runtime.Serialization" 
#r "mscorlib" 
#r "../../../../packages/prozper/System.Runtime.Serialization.Primitives/lib/net46/System.Runtime.Serialization.Primitives.dll" 