#load "System.Reflection.Emit.fsx" 
#load "System.Reflection.Emit.Lightweight.fsx" 
#load "System.Runtime.Serialization.Primitives.fsx" 
#load "System.Threading.Tasks.Extensions.fsx" 
#load "System.ValueTuple.fsx" 
#r "System" 
#r "System.Core" 
#r "../../../../packages/test2/MessagePack/lib/net45/MessagePack.dll" 