#load "Microsoft.AspNetCore.Mvc.Razor.Extensions.csx" 
#load "Microsoft.AspNetCore.Mvc.ViewFeatures.csx" 
#load "Microsoft.AspNetCore.Razor.Runtime.csx" 
#load "Microsoft.CodeAnalysis.CSharp.csx" 
#load "Microsoft.CodeAnalysis.Razor.csx" 
#load "Microsoft.Extensions.Caching.Memory.csx" 
#load "Microsoft.Extensions.FileProviders.Composite.csx" 