#load "Microsoft.AspNetCore.Mvc.Razor.Extensions.fsx" 
#load "Microsoft.AspNetCore.Mvc.ViewFeatures.fsx" 
#load "Microsoft.AspNetCore.Razor.Runtime.fsx" 
#load "Microsoft.CodeAnalysis.CSharp.fsx" 
#load "Microsoft.CodeAnalysis.Razor.fsx" 
#load "Microsoft.Extensions.Caching.Memory.fsx" 
#load "Microsoft.Extensions.FileProviders.Composite.fsx" 