#load "Microsoft.AspNetCore.Hosting.Abstractions.fsx" 
#load "Microsoft.AspNetCore.Http.Extensions.fsx" 
#load "Microsoft.Extensions.Configuration.Abstractions.fsx" 
#load "Microsoft.Extensions.FileProviders.Abstractions.fsx" 
#load "Microsoft.Extensions.Options.fsx" 