#load "Microsoft.ApplicationInsights.fsx" 
#load "Microsoft.Extensions.PlatformAbstractions.fsx" 
#load "System.Data.SqlClient.fsx" 
#load "System.Diagnostics.DiagnosticSource.fsx" 
#load "System.Diagnostics.StackTrace.fsx" 
#r "../../../../packages/test2/Microsoft.ApplicationInsights.DependencyCollector/lib/net45/Microsoft.AI.DependencyCollector.dll" 