#load "System.Diagnostics.DiagnosticSource.csx" 
#load "System.Diagnostics.StackTrace.csx" 
#load "System.Net.Requests.csx" 
#r "System.Net.Http" 
#r "../../../../packages/test2/Microsoft.ApplicationInsights/lib/net46/Microsoft.ApplicationInsights.dll" 