#load "Microsoft.AspNetCore.Identity.csx" 
#load "Microsoft.AspNetCore.Mvc.csx" 
#load "Microsoft.AspNetCore.StaticFiles.csx" 
#load "Microsoft.Extensions.FileProviders.Embedded.csx" 
#load "Microsoft.Extensions.Identity.Stores.csx" 