#load "Microsoft.AspNetCore.Authentication.Abstractions.fsx" 
#load "Microsoft.AspNetCore.Hosting.Abstractions.fsx" 
#load "Microsoft.AspNetCore.Http.Abstractions.fsx" 
#load "Microsoft.Extensions.Configuration.Abstractions.fsx" 
#load "WebSharper.fsx" 