#load "System.Diagnostics.Tracing.fsx" 
#load "System.Globalization.fsx" 
#load "System.IO.fsx" 
#load "System.IO.FileSystem.fsx" 
#r "Microsoft.CSharp" 
#r "System" 
#r "../../../../packages/prozper/Microsoft.IdentityModel.Logging/lib/net461/Microsoft.IdentityModel.Logging.dll" 