#load "HtmlAgilityPack.fsx" 
#load "System.Xml.XDocument.fsx" 
#load "WebSharper.fsx" 
#r "../../../packages/WebSharper.UI/lib/netstandard2.0/WebSharper.UI.Templating.Common.dll" 
#r "../../../packages/WebSharper.UI/lib/netstandard2.0/WebSharper.UI.dll" 
#r "../../../packages/WebSharper.UI/lib/netstandard2.0/WebSharper.UI.Templating.Runtime.dll" 
#r "../../../packages/WebSharper.UI/lib/netstandard2.0/WebSharper.UI.Templating.dll" 