#load "HtmlAgilityPack.csx" 
#load "WebSharper.csx" 
#r "../../../../packages/websharper47/WebSharper.UI/lib/netstandard2.0/WebSharper.UI.Templating.Common.dll" 
#r "../../../../packages/websharper47/WebSharper.UI/lib/netstandard2.0/WebSharper.UI.dll" 
#r "../../../../packages/websharper47/WebSharper.UI/lib/netstandard2.0/WebSharper.UI.Templating.Runtime.dll" 
#r "../../../../packages/websharper47/WebSharper.UI/lib/netstandard2.0/WebSharper.UI.Templating.dll" 