#load "Microsoft.AspNetCore.Authentication.fsx" 
#load "Microsoft.AspNetCore.Diagnostics.fsx" 
#load "Microsoft.AspNetCore.Hosting.Abstractions.fsx" 
#load "Newtonsoft.Json.fsx" 
#load "System.Text.RegularExpressions.fsx" 
#load "System.Xml.XmlSerializer.fsx" 
#load "TaskBuilder.fs.fsx" 
#r "../../../../packages/test/Giraffe/lib/net461/Giraffe.dll" 