#load "Microsoft.IdentityModel.JsonWebTokens.csx" 
#load "Microsoft.IdentityModel.Tokens.csx" 
#load "Newtonsoft.Json.csx" 
#r "Microsoft.CSharp" 
#r "System" 
#r "../../../../packages/test/System.IdentityModel.Tokens.Jwt/lib/net461/System.IdentityModel.Tokens.Jwt.dll" 