#load "System.Drawing.Common.fsx" 
#r "../../../../packages/other/OpenCvSharp3-AnyCPU/lib/net461/OpenCvSharp.dll" 
#r "../../../../packages/other/OpenCvSharp3-AnyCPU/lib/net461/OpenCvSharp.Extensions.dll" 
#r "../../../../packages/other/OpenCvSharp3-AnyCPU/lib/net461/OpenCvSharp.Blob.dll" 
#r "../../../../packages/other/OpenCvSharp3-AnyCPU/lib/net461/OpenCvSharp.UserInterface.dll" 