#load "System.Buffers.csx" 
#load "System.Formats.Asn1.csx" 
#load "System.Memory.csx" 
#load "System.Security.Cryptography.Cng.csx" 
#r "System.Security" 
#r "../../../../packages/other/System.Security.Cryptography.Pkcs/lib/net461/System.Security.Cryptography.Pkcs.dll" 