#load "System.Resources.ResourceManager.fsx" 
#load "System.Runtime.fsx" 
#load "System.Runtime.Handles.fsx" 
#load "System.Runtime.InteropServices.fsx" 
#load "System.Security.Cryptography.Primitives.fsx" 
#load "System.Text.Encoding.fsx" 
#load "System.Threading.fsx" 
#r "../../../../packages/other/System.Security.SecureString/lib/net46/System.Security.SecureString.dll" 